/**
 * Central configuration for all entity roles in TraceChain
 * This drives form generation, routing, and UI across the app
 */

export const ENTITY_ROLES = [
  {
    id: 'miner',
    label: 'Miner',
    prefix: 'MIN',
    icon: 'HardHat',
    description: 'Licensed mine owners (small, medium, or large scale)',
    profileType: 'Company',
    color: '#004C99',
  },
  {
    id: 'artisan',
    label: 'Artisan',
    prefix: 'ART',
    icon: 'Pickaxe',
    description: 'Artisanal and small-scale miners',
    profileType: 'Individual',
    color: '#005BBB',
  },
  {
    id: 'aggregator',
    label: 'Aggregator',
    prefix: 'AGG',
    icon: 'PackagePlus',
    description: 'Mineral aggregation entities',
    profileType: 'Individual or Organization',
    color: '#006ECC',
  },
  {
    id: 'processing_center',
    label: 'Processing Center',
    prefix: 'PRC',
    icon: 'Factory',
    description: 'Mineral processing and refining facilities',
    profileType: 'Organization',
    color: '#0082DD',
  },
  {
    id: 'assay',
    label: 'Assay',
    prefix: 'ASY',
    icon: 'FlaskConical',
    description: 'Mineral testing and assay laboratories',
    profileType: 'Organization',
    color: '#0095EE',
  },
  {
    id: 'logistics',
    label: 'In-land Logistics',
    prefix: 'LOG',
    icon: 'Truck',
    description: 'Warehousing and inland transport services',
    profileType: 'Organization',
    color: '#00A8FF',
  },
  {
    id: 'freight',
    label: 'Freight',
    prefix: 'FRT',
    icon: 'Globe',
    description: 'Export and international freight services',
    profileType: 'Organization',
    color: '#00BBFF',
  },
  {
    id: 'security',
    label: 'Security',
    prefix: 'SEC',
    icon: 'ShieldCheck',
    description: 'Security and escort service providers',
    profileType: 'Organization',
    color: '#00B3A4',
  },
]

export const ADMIN_ROLES = [
  {
    id: 'admin',
    label: 'Admin',
    prefix: 'ADM',
    description: 'Super administrator — full system access',
  },
  {
    id: 'inspector',
    label: 'Inspector',
    prefix: 'INS',
    description: 'Verifies and approves entity registrations',
  },
]

// Common fields shared by ALL roles
export const COMMON_FIELDS = [
  // Identity & Access
  { name: 'full_name', label: 'Full Legal Name', type: 'text', required: true, group: 'Identity' },
  { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true, group: 'Identity' },
  { name: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female', 'Prefer not to say'], required: true, group: 'Identity' },
  { name: 'email', label: 'Email Address', type: 'email', required: true, group: 'Identity' },
  { name: 'phone', label: 'Phone Number', type: 'tel', required: true, group: 'Identity' },
  { name: 'password', label: 'Password', type: 'password', required: true, group: 'Identity' },
  { name: 'country', label: 'Country', type: 'text', required: true, group: 'Location' },
  { name: 'state', label: 'State / Region', type: 'text', required: true, group: 'Location' },
  { name: 'lga', label: 'Local Government Area (LGA)', type: 'text', required: true, group: 'Location' },
  { name: 'physical_address', label: 'Physical Address', type: 'text', required: true, group: 'Location' },
  { name: 'location_gps', label: 'GPS Location (optional)', type: 'text', required: false, group: 'Location', placeholder: 'e.g. 6.5244, 3.3792' },
  { name: 'id_type', label: 'Government-Issued ID Type', type: 'select', options: ['National ID', 'Passport', "Driver's License", 'Voter\'s Card', 'Other'], required: true, group: 'Documents' },
  { name: 'id_number', label: 'ID Number', type: 'text', required: true, group: 'Documents' },
  { name: 'id_document', label: 'Upload ID Document', type: 'file', required: true, group: 'Documents', accept: '.jpg,.jpeg,.png,.pdf' },
  { name: 'profile_photo', label: 'Profile Photo', type: 'file', required: false, group: 'Documents', accept: '.jpg,.jpeg,.png' },
]

// Role-specific fields
export const ROLE_SPECIFIC_FIELDS = {
  artisan: [
    { name: 'local_name', label: 'Local / Community Name', type: 'text', required: false },
    { name: 'miner_alias', label: 'Nickname / Miner Alias', type: 'text', required: false },
    { name: 'years_experience', label: 'Years of Mining Experience', type: 'number', required: true },
    { name: 'primary_minerals', label: 'Primary Mineral(s) Mined', type: 'text', required: true, placeholder: 'e.g. Gold, Coltan' },
    { name: 'mining_method', label: 'Mining Method', type: 'select', options: ['Manual', 'Shallow Pit', 'Riverbed', 'Other'], required: true },
    { name: 'tools_used', label: 'Tools Used', type: 'text', required: false, placeholder: 'List manual tools used' },
    { name: 'mining_site_name', label: 'Mining Site Name(s)', type: 'text', required: true },
    { name: 'site_gps_coordinates', label: 'Mining Site GPS Coordinates', type: 'text', required: false },
    { name: 'land_ownership', label: 'Land Ownership Status', type: 'select', options: ['Community', 'Leased', 'Informal'], required: true },
    { name: 'cooperative_member', label: 'Cooperative Membership', type: 'select', options: ['Yes', 'No'], required: true },
    { name: 'cooperative_name', label: 'Cooperative Name (if any)', type: 'text', required: false },
    { name: 'safety_training', label: 'Safety Training Received', type: 'select', options: ['Yes', 'No'], required: true },
    { name: 'ppe_usage', label: 'PPE Usage Level', type: 'select', options: ['None', 'Partial', 'Full'], required: true },
  ],

  miner: [
    { name: 'mining_license_number', label: 'Mining License Number', type: 'text', required: true },
    { name: 'license_authority', label: 'License Issuing Authority', type: 'text', required: true },
    { name: 'license_category', label: 'License Category', type: 'select', options: ['ASM', 'Small-scale', 'Medium-scale', 'Large-scale'], required: true },
    { name: 'license_validity', label: 'License Validity Period', type: 'text', required: true, placeholder: 'e.g. Jan 2024 – Dec 2026' },
    { name: 'licensed_minerals', label: 'Licensed Mineral(s)', type: 'text', required: true },
    { name: 'license_area_size', label: 'License Area Size (Cadastral Units)', type: 'text', required: false },
    { name: 'lease_coordinates', label: 'Mining Lease Coordinates', type: 'text', required: false },
    { name: 'mining_method', label: 'Mining Method', type: 'select', options: ['Open Pit', 'Underground', 'Alluvial', 'Other'], required: true },
    { name: 'monthly_capacity', label: 'Estimated Monthly Production Capacity', type: 'text', required: false },
    { name: 'env_permit', label: 'Environmental Permit No. / Community Consent Letter', type: 'text', required: false },
    { name: 'hs_certificate', label: 'Health & Safety Compliance Certificate', type: 'text', required: false },
    { name: 'community_dev_agreement', label: 'Community Development Agreement', type: 'select', options: ['Yes', 'No'], required: true },
    { name: 'num_workers', label: 'Number of Workers Employed', type: 'number', required: false },
    { name: 'onsite_security', label: 'Onsite Security Presence', type: 'select', options: ['Yes', 'No'], required: true },
  ],

  assay: [
    { name: 'lab_name', label: 'Laboratory Name', type: 'text', required: true },
    { name: 'lab_registration_number', label: 'Laboratory Registration Number', type: 'text', required: true },
    { name: 'accreditation_body', label: 'Accreditation Body', type: 'text', required: true, placeholder: 'e.g. ISO, National Standards Org' },
    { name: 'accreditation_cert_number', label: 'Accreditation Certificate Number', type: 'text', required: true },
    { name: 'testing_methods', label: 'Testing Methods Used', type: 'text', required: true, placeholder: 'e.g. XRF, ICP-MS, Fire Assay' },
    { name: 'minerals_tested', label: 'Minerals Tested', type: 'text', required: true },
    { name: 'max_throughput', label: 'Maximum Sample Throughput (per day/week)', type: 'text', required: false },
    { name: 'chain_of_custody', label: 'Sample Chain of Custody Process', type: 'textarea', required: false },
    { name: 'avg_turnaround', label: 'Average Turnaround Time', type: 'text', required: false },
    { name: 'calibration_schedule', label: 'Calibration Schedule', type: 'text', required: false },
    { name: 'lead_officer', label: 'Lead Assay Officer Name & Certification', type: 'text', required: true },
    { name: 'data_integrity', label: 'Data Integrity Controls', type: 'select', options: ['Manual', 'Digital', 'Hybrid'], required: true },
    { name: 'accuracy_rate', label: 'Historical Accuracy Rate (if available)', type: 'text', required: false },
  ],

  processing_center: [
    { name: 'facility_name', label: 'Facility Name', type: 'text', required: true },
    { name: 'facility_reg_number', label: 'Facility Registration Number', type: 'text', required: true },
    { name: 'processing_type', label: 'Processing Type', type: 'select', options: ['Crushing', 'Washing', 'Smelting', 'Refining', 'Other'], required: true },
    { name: 'minerals_processed', label: 'Minerals Processed', type: 'text', required: true },
    { name: 'installed_capacity', label: 'Installed Processing Capacity', type: 'text', required: false },
    { name: 'avg_recovery_rate', label: 'Average Recovery Rate (%)', type: 'number', required: false },
    { name: 'waste_handling', label: 'Waste Handling Method', type: 'text', required: false },
    { name: 'env_compliance_permit', label: 'Environmental Compliance Permit', type: 'text', required: false },
    { name: 'energy_source', label: 'Energy Source', type: 'select', options: ['Diesel', 'Grid', 'Solar', 'Hybrid'], required: true },
    { name: 'input_source_types', label: 'Input Source Types', type: 'text', required: false, placeholder: 'e.g. ASM, Licensed miners, Aggregators' },
    { name: 'output_product_type', label: 'Output Product Type', type: 'select', options: ['Concentrate', 'Doré', 'Refined', 'Other'], required: true },
    { name: 'quality_control', label: 'Quality Control Process', type: 'textarea', required: false },
    { name: 'onsite_assay', label: 'Onsite Assay Capability', type: 'select', options: ['Yes', 'No'], required: true },
  ],

  aggregator: [
    { name: 'aggregator_reg_number', label: 'Aggregator Registration Number', type: 'text', required: true },
    { name: 'operating_regions', label: 'Operating Regions', type: 'text', required: true },
    { name: 'minerals_aggregated', label: 'Minerals Aggregated', type: 'text', required: true },
    { name: 'avg_monthly_volume', label: 'Average Monthly Volume Handled', type: 'text', required: false },
    { name: 'source_mix', label: 'Source Mix (% ASM vs Licensed)', type: 'text', required: false, placeholder: 'e.g. 60% ASM, 40% Licensed' },
    { name: 'storage_facility', label: 'Storage Facility Details', type: 'text', required: false },
    { name: 'aggregating_location', label: 'Aggregating Location', type: 'text', required: true },
    { name: 'inventory_management', label: 'Inventory Management Method', type: 'text', required: false },
    { name: 'weight_verification', label: 'Weight Verification Method', type: 'text', required: false },
    { name: 'pricing_model', label: 'Pricing Model', type: 'select', options: ['Spot', 'Fixed Margin', 'Commission', 'Other'], required: false },
    { name: 'downstream_buyers', label: 'Downstream Buyers', type: 'text', required: false, placeholder: 'e.g. Processing centers, Exporters' },
    { name: 'compliance_history', label: 'Compliance History (self-reported)', type: 'textarea', required: false },
  ],

  freight: [
    { name: 'freight_company_name', label: 'Freight Company Name', type: 'text', required: true },
    { name: 'transport_license', label: 'Transport License Number', type: 'text', required: true },
    { name: 'transport_modes', label: 'Transport Modes', type: 'text', required: true, placeholder: 'e.g. Truck, Rail, Inland Waterway' },
    { name: 'fleet_details', label: 'Vehicle Fleet Details (IDs, Plate Numbers, Capacity)', type: 'textarea', required: false },
    { name: 'driver_registry', label: 'Driver Registry (IDs + Licenses)', type: 'textarea', required: false },
    { name: 'insurance_coverage', label: 'Insurance Coverage Details', type: 'text', required: false },
    { name: 'route_coverage', label: 'Route Coverage Areas', type: 'text', required: true },
    { name: 'avg_transit_time', label: 'Average Transit Time', type: 'text', required: false },
    { name: 'cargo_sealing', label: 'Cargo Sealing Method', type: 'text', required: false },
    { name: 'tracking_capability', label: 'Tracking Capability', type: 'select', options: ['GPS', 'Manual', 'None'], required: true },
    { name: 'incident_reporting', label: 'Incident Reporting Process', type: 'textarea', required: false },
  ],

  logistics: [
    { name: 'logistics_company_name', label: 'Logistics Company Name', type: 'text', required: true },
    { name: 'warehouse_locations', label: 'Warehouse Locations (GPS)', type: 'text', required: true },
    { name: 'warehouse_capacity', label: 'Warehouse Capacity', type: 'text', required: false },
    { name: 'storage_type', label: 'Storage Type', type: 'select', options: ['Bonded', 'Non-Bonded'], required: true },
    { name: 'export_handling', label: 'Export Handling Capability', type: 'select', options: ['Yes', 'No'], required: true },
    { name: 'customs_reg_number', label: 'Customs Registration Number', type: 'text', required: false },
    { name: 'inventory_reconciliation', label: 'Inventory Reconciliation Process', type: 'textarea', required: false },
    { name: 'batch_segregation', label: 'Batch Segregation Controls', type: 'text', required: false },
    { name: 'export_docs_handled', label: 'Export Documentation Handled', type: 'text', required: false },
    { name: 'chain_of_custody', label: 'Chain of Custody Controls', type: 'text', required: false },
    { name: 'insurance_coverage', label: 'Insurance Coverage', type: 'text', required: false },
    { name: 'avg_storage_duration', label: 'Average Storage Duration', type: 'text', required: false },
  ],

  security: [
    { name: 'security_company_name', label: 'Security Company Name', type: 'text', required: true },
    { name: 'security_license', label: 'Security License Number', type: 'text', required: true },
    { name: 'license_authority', label: 'License Issuing Authority', type: 'text', required: true },
    { name: 'armed_classification', label: 'Armed / Unarmed Classification', type: 'select', options: ['Armed', 'Unarmed', 'Both'], required: true },
    { name: 'deployment_areas', label: 'Areas of Deployment', type: 'text', required: true, placeholder: 'e.g. Mine, Transport, Warehouse' },
    { name: 'num_personnel', label: 'Number of Personnel', type: 'number', required: false },
    { name: 'vetting_process', label: 'Personnel Vetting Process', type: 'textarea', required: false },
    { name: 'incident_response', label: 'Incident Response Capability', type: 'text', required: false },
    { name: 'escort_services', label: 'Escort Services Offered', type: 'select', options: ['Yes', 'No'], required: true },
    { name: 'communication_equipment', label: 'Communication Equipment Used', type: 'text', required: false },
    { name: 'incident_workflow', label: 'Incident Reporting Workflow', type: 'textarea', required: false },
    { name: 'mining_experience', label: 'Past Deployment Experience (Mining-specific)', type: 'textarea', required: false },
  ],
}
